---
- name: Gather zfs filesystem attributes for {% if zfs_parent_fs is defined %}{{ zfs_parent_fs }}/{% endif %}{{ fs.name }}
  zfs_facts:
    name: "{% if zfs_parent_fs is defined %}{{ zfs_parent_fs }}/{% endif %}{{ fs.name }}"
    properties: "utf8only,normalization,casesensitivity"
  failed_when: False
  register: fs_exists

# this task fails when the filesystem already exists and some attribute in {utf8only, normalization, casesensitivity} is already set and has a differing value than the variables dictate. This is done because these attributes cannot be changed after creation
- name: Fail if readonly attributes would be changed on {% if zfs_parent_fs is defined %}{{ zfs_parent_fs }}/{% endif %}{{ fs.name }}
  fail:
    msg: "Tried to change readonly zfs attribute on already-existing filesystem {% if zfs_parent_fs is defined %}{{ zfs_parent_fs }}/{% endif %}{{ fs.name }}\n {{ansible_zfs_datasets[0]}}"
  when: >
    (fs_exists.msg is not defined) and
    (   ((fs.attributes is defined and fs.attributes.utf8only is defined or default is defined and default.utf8only is defined) and ansible_zfs_datasets[0].utf8only != fs.attributes.utf8only |default(zfs_storage_defaults.utf8only) |default(ansible_zfs_datasets[0].utf8only)) or
        ((fs.attributes is defined and fs.attributes.normalization is defined or default is defined and default.normalization is defined) and ansible_zfs_datasets[0].normalization != fs.attributes.normalization |default(zfs_storage_defaults.normalization) |default(ansible_zfs_datasets[0].normalization)) or
        ((fs.attributes is defined and fs.attributes.casesensitivity is defined or default is defined and default.casesensitivity is defined) and ansible_zfs_datasets[0].casesensitivity != fs.attributes.casesensitivity |default(zfs_storage_defaults.casesensitivity) |default(ansible_zfs_datasets[0].casesensitivity)))

- name: Configure filesystem {% if zfs_parent_fs is defined %}{{ zfs_parent_fs }}/{% endif %}{{ fs.name }}
  zfs:
    name: "{% if zfs_parent_fs is defined %}{{ zfs_parent_fs }}/{% endif %}{{ fs.name }}"
    state: present
    extra_zfs_properties:
      #these three attributes are only settable when creating the filesystem
      utf8only: "{% if fs_exists.msg is defined %}{{ fs.attributes.utf8only|default(zfs_storage_defaults.utf8only) |default(omit) }}{% else %}{{fs_exists.somethingnotdefined |default(omit)}}{% endif %}"
      normalization: "{% if fs_exists.msg is defined %}{{ fs.attributes.normalization|default(zfs_storage_defaults.normalization) |default(omit) }}{% else %}{{fs_exists.somethingnotdefined |default(omit)}}{% endif %}"
      casesensitivity: "{% if fs_exists.msg is defined %}{{ fs.attributes.casesensitivity|default(zfs_storage_defaults.casesensitivity) |default(omit) }}{% else %}{{fs_exists.somethingnotdefined |default(omit)}}{% endif %}"

      aclinherit: "{{ fs.attributes.aclinherit |default(zfs_storage_defaults.aclinherit) |default(zfs_base_defaults.aclinherit) }}"
      acltype: "{{ fs.attributes.acltype |default(zfs_storage_defaults.acltype) |default(zfs_base_defaults.acltype) }}"
      atime: "{{ fs.attributes.atime |default(zfs_storage_defaults.atime) |default(zfs_base_defaults.atime) }}"
      canmount: "{{ fs.attributes.canmount |default(zfs_storage_defaults.canmount) |default(zfs_base_defaults.canmount) }}"
      checksum: "{{ fs.attributes.checksum |default(zfs_storage_defaults.checksum) |default(zfs_base_defaults.checksum) }}"
      compression: "{{ fs.attributes.compression |default(zfs_storage_defaults.compression) |default(zfs_base_defaults.compression) }}"
      copies: "{{ fs.attributes.copies |default(zfs_storage_defaults.copies) |default(zfs_base_defaults.copies) }}"
      dedup: "{{ fs.attributes.dedup |default(zfs_storage_defaults.dedup) |default(zfs_base_defaults.dedup) }}"
      devices: "{{ fs.attributes.devices |default(zfs_storage_defaults.devices) |default(zfs_base_defaults.devices) }}"
      exec: "{{ fs.attributes.exec |default(zfs_storage_defaults.exec) |default(zfs_base_defaults.exec) }}"
      filesystem_limit: "{{ fs.attributes.filesystem_limit |default(zfs_storage_defaults.filesystem_limit) |default(zfs_base_defaults.filesystem_limit) }}"
      logbias: "{{ fs.attributes.logbias |default(zfs_storage_defaults.logbias) |default(zfs_base_defaults.logbias) }}"
      #mountpoint is omitted by default as it is generated by ZFS
      mountpoint: "{{ fs.attributes.mountpoint |default(zfs_storage_defaults.mountpoint) |default(omit) }}"
      overlay: "{{ fs.attributes.overlay |default(zfs_storage_defaults.overlay) |default(zfs_base_defaults.overlay) }}"
      primarycache: "{{ fs.attributes.primarycache |default(zfs_storage_defaults.primarycache) |default(zfs_base_defaults.primarycache) }}"
      quota: "{{ fs.attributes.quota |default(zfs_storage_defaults.quota) |default(zfs_base_defaults.quota) }}"
      snapshot_limit: "{{ fs.attributes.snapshot_limit |default(zfs_storage_defaults.snapshot_limit) |default(zfs_base_defaults.snapshot_limit) }}"
      readonly: "{{ fs.attributes.readonly |default(zfs_storage_defaults.readonly) |default(zfs_base_defaults.readonly) }}"
      recordsize: "{{ fs.attributes.recordsize |default(zfs_storage_defaults.recordsize) |default(zfs_base_defaults.recordsize) }}"
      redundant_metadata: "{{ fs.attributes.redundant_metadata |default(zfs_storage_defaults.redundant_metadata) |default(zfs_base_defaults.redundant_metadata) }}"
      refquota: "{{ fs.attributes.refquota |default(zfs_storage_defaults.refquota) |default(zfs_base_defaults.refquota) }}"
      refreservation: "{{ fs.attributes.refreservation |default(zfs_storage_defaults.refreservation) |default(zfs_base_defaults.refreservation) }}"
      relatime: "{{ fs.attributes.relatime |default(zfs_storage_defaults.relatime) |default(zfs_base_defaults.relatime) }}"
      reservation: "{{ fs.attributes.reservation |default(zfs_storage_defaults.reservation) |default(zfs_base_defaults.reservation) }}"
      secondarycache: "{{ fs.attributes.secondarycache |default(zfs_storage_defaults.secondarycache) |default(zfs_base_defaults.secondarycache) }}"
      setuid: "{{ fs.attributes.setuid |default(zfs_storage_defaults.setuid) |default(zfs_base_defaults.setuid) }}"
      sharesmb: "{{ fs.attributes.sharesmb |default(zfs_storage_defaults.sharesmb) |default(zfs_base_defaults.sharesmb) }}"
      sharenfs: "{{ fs.attributes.sharenfs |default(zfs_storage_defaults.sharenfs) |default(zfs_base_defaults.sharenfs) }}"
      snapdev: "{{ fs.attributes.snapdev |default(zfs_storage_defaults.snapdev) |default(zfs_base_defaults.snapdev) }}"
      snapdir: "{{ fs.attributes.snapdir |default(zfs_storage_defaults.snapdir) |default(zfs_base_defaults.snapdir) }}"
      sync: "{{ fs.attributes.sync |default(zfs_storage_defaults.sync) |default(zfs_base_defaults.sync) }}"
      xattr: "{{ fs.attributes.xattr |default(zfs_storage_defaults.xattr) |default(zfs_base_defaults.xattr) }}"

      "com.sun:auto-snapshot": "{{ fs.attributes.com_sun_auto_snapshot |default(zfs_storage_defaults.com_sun_auto_snapshot) |default(zfs_base_defaults.com_sun_auto_snapshot) | lower }}"
      "com.sun:auto-snapshot:frequent": "{{ fs.attributes.com_sun_auto_snapshot_frequent |default(zfs_storage_defaults.com_sun_auto_snapshot_frequent) |default(zfs_base_defaults.com_sun_auto_snapshot_frequent) | lower }}"
      "com.sun:auto-snapshot:hourly": "{{ fs.attributes.com_sun_auto_snapshot_hourly |default(zfs_storage_defaults.com_sun_auto_snapshot_hourly) |default(zfs_base_defaults.com_sun_auto_snapshot_hourly) | lower }}"
      "com.sun:auto-snapshot:daily": "{{ fs.attributes.com_sun_auto_snapshot_daily |default(zfs_storage_defaults.com_sun_auto_snapshot_daily) |default(zfs_base_defaults.com_sun_auto_snapshot_daily) | lower }}"
      "com.sun:auto-snapshot:weekly": "{{ fs.attributes.com_sun_auto_snapshot_weekly |default(zfs_storage_defaults.com_sun_auto_snapshot_weekly) |default(zfs_base_defaults.com_sun_auto_snapshot_weekly) | lower }}"
      "com.sun:auto-snapshot:monthly": "{{ fs.attributes.com_sun_auto_snapshot_monthly |default(zfs_storage_defaults.com_sun_auto_snapshot_monthly) |default(zfs_base_defaults.com_sun_auto_snapshot_monthly) | lower }}"
