---
- name: Install NFS server package
  apt:
    name: nfs-kernel-server
  when: ansible_pkg_mgr == "apt"
  notify:
    - Restart NFS server

- name: Enable NFS server
  service:
    name: nfs-kernel-server.service
    enabled: True
  when: ansible_service_mgr == "systemd"

- name: Create NFS exports.d directory
  file:
    path: /etc/exports.d/
    state: directory
